font_name   = "Meiryo UI"
tab_title   = "modify as you like"
task_number = 50
start_date  = "2006/08/01"
end_date    = "2006/10/30"

holidays = [
  "2025/01/01", # New Year's Day
  "2025/01/02", # 
  "2025/01/03", # 
  "2025/01/13", # Coming-of-Age Day
  "2025/02/11", # National Foundation Day
  "2025/02/23", # The Emperor's Birthday
  "2025/02/24", # Substitute Public Holiday
  "2025/03/20", # Vernal Equinox Day
  "2025/04/29", # Showa Day
  "2025/05/03", # Constitution Memorial Day
  "2025/05/04", # Greenery Day
  "2025/05/05", # Children's Day
  "2025/05/06", # Substitute Public Holiday
  "2025/07/21", # Marine Day
  "2025/08/11", # Mountain Day
  "2025/09/15", # Respect for the Aged Day
  "2025/09/23", # Autumnal Equinox Day
  "2025/10/13", # Sports Day
  "2025/11/03", # Culture Day
  "2025/11/23", # Labour Thanksgiving Day
  "2025/11/24", # Substitute Public Holiday
  "2025/12/29", # 
  "2025/12/30", # 
  "2025/12/31", # 

  "2026/01/01", # New Year's Day
  "2026/01/02", # 
  "2026/01/03", # 
  "2026/01/12", # Coming-of-Age Day
  "2026/02/11", # National Foundation Day
  "2026/02/23", # The Emperor's Birthday
  "2026/03/20", # Vernal Equinox Day
  "2026/04/29", # Showa Day
  "2026/05/03", # Constitution Memorial Day
  "2026/05/04", # Greenery Day
  "2026/05/05", # Children's Day
  "2026/05/06", # Substitute Public Holiday
  "2026/07/20", # Marine Day
  "2026/08/11", # Mountain Day
  "2026/09/21", # Respect for the Aged Day
  "2026/09/22", # Substitute Public Holiday
  "2026/09/23", # Autumnal Equinox Day
  "2026/10/12", # Sports Day
  "2026/11/03", # Culture Day
  "2026/11/23", # Labour Thanksgiving Day
  "2026/12/29", # 
  "2026/12/30", # 
  "2026/12/31", # 
]
