[project]
name = "excel-gantt-template-generator"
version = "1.0.0"
description = "Excel template file generator for gantt chart"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "openpyxl>=3.1.5",
]
